C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/ObjectShaders/ObjectShaderVS.vert -o shaders/ObjectShaders/ObjectShaderVS.spv
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/ObjectShaders/ObjectSkinnedVS.vert -o shaders/ObjectShaders/ObjectSkinnedVS.spv
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/ObjectShaders/ObjectTexturedFS.frag -o shaders/ObjectShaders/ObjectTexturedFS.spv
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/PostProcessing/quad.vert -o shaders/PostProcessing/quadvert.spv
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/PostProcessing/quad.frag -o shaders/PostProcessing/quadfrag.spv
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/ObjectShaders/ObjectBasicFS.frag -o shaders/ObjectShaders/ObjectBasicFS.spv
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/ObjectShaders/ObjectVolumetricVS.vert -o shaders/ObjectShaders/ObjectVolumetricVS.spv
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/ObjectShaders/ObjectVolumetricFS.frag -o shaders/ObjectShaders/ObjectVolumetricFS.spv
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/ComputeShaders/simple.comp -o shaders/ComputeShaders/compute.spv
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/ComputeShaders/MeshtoSdf.comp -o shaders/ComputeShaders/MeshtoSdf.spv
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/ComputeShaders/sdfCompute.comp -o shaders/ComputeShaders/sdfCompute.spv 
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/ComputeShaders/sdfCompute2.comp -o shaders/ComputeShaders/sdfCompute2.spv
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/ComputeShaders/GaussianFluidSim.comp -o shaders/ComputeShaders/GaussianFluidSim.spv 
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/PostProcessing/VolumePassVS.vert -o shaders/PostProcessing/VolumePassVS.spv
C:/VulkanSDK/1.2.189.2/Bin/glslc.exe shaders/PostProcessing/VolumePassFS.frag -o shaders/PostProcessing/VolumePassFS.spv
